language: python

sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.9"

install:
  - pip install tox tox-travis

# Some tests may require accessing the database from multiple threads
# (see #296), which isn't supported by the sqlite3 engine. Run the tests with
# Postgres in CI to allow full test coverage.
services:
  postgresql

before_script:
  - psql -c 'create database waffle_test;' -U postgres

env:
  - DATABASE_URL=postgres://postgres@localhost:5432/waffle_test

script:
  - tox

deploy:
  provider: pypi
  user: django-waffle
  password:
    secure: sQzN+jn7JdkIJbXsjS1uRueNVo2AsPh2iJChDAisWu8qFRMFREbHCKRu33+WZ9Vbw0NuRC2Wl2DknPTKYBtMq+4YzbKyRLAXvf/qAzWwcbjQsPAz1bQnfDBbOhcewiltfVf3AEbsq97NdKhOS4+T0R3/eqMhbAM9PVP2WO78cvA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6

after_success:
 - coveralls
 - codecov
